### ISSUE TITLE
Allow for non cluster-admin users to run migrations

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#388]
This is a tracking issue for all the work required to allow non cluster-admin users to run migrations. The design document is here: https://github.com/konveyor/enhancements/blob/master/enhancements/non-admin/cam-non-admin-design.md

Feature Branch across all repos:
* https://github.com/konveyor/mig-controller/tree/non-admin
* https://github.com/konveyor/mig-ui/tree/non-admin
* https://github.com/konveyor/mig-operator/tree/non-admin

**mig-controller**:
- [x] #389  - Enable migplan controller to take in a user's identity token for src + dest
- [ ] #391  - Discovery controller authorization should be using SAR checks with user's identity
- [x] #393  - Controller should pre-create destination namespaces
- [x] #470  - Add authorization phase to migration controller workflow
- [x] #471  - Update all controllers to watch resources in the sandbox namespace
- [x] #472  - Investigate singleton discovery controller vs 1 per controller
- [x] #504 - Update CAM configuration to allow for a blacklist of cluster-scoped resources to not allow non-admin user to migrate
- [x] #512 - Add MigToken CRD
- [x] #544 - Add helper script to create MigTenant for testing
- [x] #545 - Update MigToken CRD to include OAuth details
- [x]  allow mig-controller to watch all namespaces 
- [ ] #561 - Improve tokenreview/SAR check workflow
- [ ] #550 - Dynamically generate list of GVK's that require SAR check
- [ ] #555 - add ProjectRequest SAR check to validite MigToken
- [ ] #570 - Restricting object references to non-admin namespaces

**mig-operator**
- [x] https://github.com/konveyor/mig-operator/issues/253 - Use migration-controller SA rather than cluster-admin
- [x] https://github.com/konveyor/mig-operator/issues/285 - Add MigrationTenant CRD
- [x] https://github.com/konveyor/mig-operator/issues/286 - Update operator to watch all namespaces for MigrationTenant creation
- [x] https://github.com/konveyor/mig-operator/issues/315 - Update Ansible roles for non-admin
- [ ] https://github.com/konveyor/mig-operator/issues/287 - Ensure that 1.2+ upgrades are possible and not breaking current installations

**mig-ui**
- [ ] https://github.com/konveyor/mig-ui/issues/789 - Break out identity creation in UI

**Velero** - Optional
- [ ] https://github.com/vmware-tanzu/velero/issues/1531 - Support concurrent Restic backups
- [ ] https://github.com/vmware-tanzu/velero/issues/487 - Support concurrent Velero backups
