### ISSUE TITLE
Make perf/scale enhancements to mig-controller

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#597]
#### Done
- [x] Implement metrics capturing k8s API requests issues - #591 
- [x] Implement liberr wrap and use logging package to make transition back to cached client easier - #595 
- [x] Capture traces showing areas of mig-controller most in need of improvement 
- [x]  Optimize `deleteLabels()` aka `EnsureLabelsDeleted` #608 
- [x]  Add RTT metric to mig-controller #606 
- [x]  Use common image registry for all MigPlans sharing a MigStorage to increase performance and cache hits for images within - #598 
- [x] Add watch verbs to mig-controller SA to resolve cached client informer permissions issues [mig-operator#412](https://github.com/konveyor/mig-operator/pull/412)
- [x]  Add metrics DB gather capability to must-gather for analysis of mig requests issued on customer clusters [must-gather#4](https://github.com/konveyor/must-gather/issues/4)
- [x]  Prior to running migration, inform user of what will be migrated with counts for each resource and size estimates - #604 
- [x] [#651 ](https://github.com/konveyor/mig-controller/pull/651)
    - Make it possible to have many MigPlans open at once without perf impact 
    - Remove remote watch system
    - Reduce frequency of heavy MigPlan processes  (PV discovery, GVK diff)
- [x] Make targeted performance improvements to controller systems based on API request catalog and benchmark results from metrics - #608
- [x] Lazy registry start to reduce overhead from idle MigPlans https://github.com/konveyor/mig-controller/pull/717

#### Depriorititized
- [ ] Reduce SelfSAR checks performed in validateSATokenPrivs 
- [ ] Evaluate all `List()` calls done from mig-controller, use labelselectors anywhere possible to reduce impact of these
- [ ] Turn cached client back on, implementing required error handling and fixing issues along the way - #622 
- [ ] Integrate direct-delivery remote watch system

**Comment by djwhatle** [comment]
## Benchmark data

**Scenario: Migration of 10x restify apps**

| Cluster          | Component                | Function                                       | Kind                             | Method          | Count |
| ---------------- | ------------------------ | ---------------------------------------------- | -------------------------------- | --------------- | ----- |
| cluster="ocp311" | component="migcluster"   | function="(\*ReconcileMigCluster).Reconcile"   | kind="SelfSubjectAccessReview"   | method="Create" | 292   |
| cluster="ocp44"  | component="migcluster"   | function="(\*ReconcileMigCluster).Reconcile"   | kind="StorageClassList"          | method="List"   | 179   |
| cluster="ocp311" | component="migcluster"   | function="(\*ReconcileMigCluster).Reconcile"   | kind="StorageClassList"          | method="List"   | 146   |
| cluster="ocp44"  | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="RestoreList"               | method="List"   | 120   |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="PodList"                   | method="List"   | 63    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="PodList"                   | method="List"   | 47    |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="DeploymentConfigList"      | method="List"   | 33    |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="Namespace"                 | method="Get"    | 33    |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="CronJobList"               | method="List"   | 30    |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="DaemonSetList"             | method="List"   | 30    |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="DeploymentList"            | method="List"   | 30    |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="JobList"                   | method="List"   | 30    |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="ReplicaSetList"            | method="List"   | 30    |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="ReplicationControllerList" | method="List"   | 30    |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="StatefulSetList"           | method="List"   | 30    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="BackupList"                | method="List"   | 22    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="DeploymentConfigList"      | method="List"   | 21    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="CronJobList"               | method="List"   | 20    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="DaemonSetList"             | method="List"   | 20    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="DeploymentConfig"          | method="Update" | 20    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="DeploymentList"            | method="List"   | 20    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="JobList"                   | method="List"   | 20    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="ReplicaSetList"            | method="List"   | 20    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="StatefulSetList"           | method="List"   | 20    |
| cluster="ocp44"  | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="PodList"                   | method="List"   | 13    |
| cluster="ocp44"  | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="PersistentVolumeClaimList" | method="List"   | 10    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="Namespace"                 | method="Get"    | 10    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="Namespace"                 | method="Update" | 10    |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="PersistentVolumeClaimList" | method="List"   | 10    |
| cluster="ocp44"  | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="SecretList"                | method="List"   | 9     |
| cluster="ocp311" | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="SecretList"                | method="List"   | 9     |
| cluster="ocp44"  | component="migplan"      | function="(\*ReconcileMigPlan).Reconcile"      | kind="Secret"                    | method="Update" | 5     |
| cluster="ocp44"  | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="Secret"                    | method="Get"    | 4     |
| cluster="ocp311" | component="migmigration" | function="(\*ReconcileMigMigration).Reconcile" | kind="Secret"                    | method="Get"    | 4     |

**Comment by djwhatle** [comment]
@jortel @alaypatel07 I was able to profile each phase in mig-controller showing a distribution of execution times with the `trace` pkg and `go tool trace`. This sample was run on a small migration. 

This information feels pretty actionable to me. Looks like the first thing I'll target will be optimization of `ensureLabelsDeleted`. I also want to profile each Mig* controller reconcile to get a runtime distribution for those.

![image](https://user-images.githubusercontent.com/7576968/89332639-bbd9b400-d661-11ea-9a00-de4a2b8e5b73.png)

**Comment by djwhatle** [comment]
@jortel @alaypatel07 more tracing info, this time showing reconcile time distributions and counts per controller.

Notice how the reconcile counts nearly match up for each controller that is watching the Mig* CRs below it. This would be useful to measure again with @jortel 's revamped remote watch system.

### Mig* sub-controller reconcile Stats: Runtime + Counts (parks-app-1, final migration)
![image](https://user-images.githubusercontent.com/7576968/89334951-54256800-d665-11ea-8bba-0c01d48e0d8d.png)

**Comment by djwhatle** [comment]
Closing this issue, the work scheduled in it for 1.4.0 has been completed. There are a few _deprioritized_ work items remaining  in the list. If we need to squeeze a bit more perf out of the controller from a # of requests issued and size of requests issued perspective those will be the places to start.
