### ISSUE TITLE
Progress Reporting Tracking Issue

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/mig-controller#686]
## Description

This issue tracks work being done on _progress reporting_.

### mig-controller

- [x] [Introduce field / condition to show progress of an ongoing phase](https://github.com/konveyor/mig-controller/issues/685)
- [x] [Implement progress reporting for Backup phases](https://github.com/konveyor/mig-controller/issues/687)
- [x] [Implement progress reporting for Restore phases](https://github.com/konveyor/mig-controller/issues/688)
- [x] [Failed stage pod conditions](https://github.com/konveyor/mig-controller/issues/657)
- [ ] [Volume snapshot progress](https://github.com/konveyor/mig-controller/issues/696)
- [ ] [Add Velero PVB, PVR to discovery service](https://github.com/konveyor/mig-controller/issues/713)
- [x] [Remove progress report from message field of MigMigration](https://github.com/konveyor/mig-controller/issues/714)

### UI
- [ ] [Support for updated itineraries](https://github.com/konveyor/mig-ui/issues/1035)

**Comment by eriknelson** [comment]
Closing as we've deprecated github based tracking issues in favor of replacing them with JIRA stories. Cooresponding JIRA story for this one found here: https://issues.redhat.com/browse/MIG-119
