### ISSUE TITLE
[MIG-249] Enhance Rollback, Enable Retry

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#704]
## Description

**Jira**: https://issues.redhat.com/browse/MIG-249

This issue tracks work being done to enhance:
- **Rollback**, so that a user can always run the next migration attempt without manual cleanup
- **Retry**, so that a user can restart a failed migration from the point of failure and skip steps they have already run

## Related issues

**Done**
- [x] [Allow user to control Rollback of a migration at will or on failure #663](https://github.com/konveyor/mig-controller/issues/663)
- [x] [Orphaned stage pods should be cleaned up at the beginning of each 'Stage', 'Final', 'Rollback' migration #700](https://github.com/konveyor/mig-controller/issues/700)
- [x] [Pending `openshift-migration` Backups, Restores, PVBs and PVRs should be removed at migration start #703](https://github.com/konveyor/mig-controller/issues/703)
- [x] [Apps should be un-quiesced at appropriate times #701](https://github.com/konveyor/mig-controller/issues/701)

**In-Progress**

**Todo**
- [ ] [Implement MigMigration retry mechanism to shorten user debugging loop #702](https://github.com/konveyor/mig-controller/issues/702)

**Comment by djwhatle** [comment]
Closing this issue, retry work is tracked in #702
