### ISSUE TITLE
[MIG-284] Direct Image Migration controller update tracker

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#721]
## Description

This issue tracks work being done on direct image migration controller that must be completed by v1.4.0.
## Must complete for v1.4.0
**High Priority**
- [x] Integrate with migmigration controller
- [ ] Progress reporting
- [x] Update resource watches + predicate logic

**Lower priority**
- [ ] Update the DIM controller to use `openshiftapiserver` CR to get registry location for OCP 4 clusters (https://github.com/konveyor/mig-controller/pull/710#discussion_r513874415)
- [ ] Extra optional validation to verify networking environment is suitable for DIM use case

## Nice to haves for v.1.4.0:

- [ ] Rework reconciliation loop to not use itinerary workflow
- [ ] Unit tests for all functions used by controller
