### ISSUE TITLE
Direct Volume Migration controller update tracker

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#722]
## Description

This issue tracks work being done on direct volume migration controller.
## Related issues

- [ ] Extra optional validation to verify networking environment is suitable for DVM use case
- [ ] Integrate with migmigration controller
- [ ] Progress reporting of rsync client
- [ ] Update resource watches + predicate logic
- [ ] Proper error handling and collection between parent+child CRs
- [ ] Correlation label integration
- [ ] Needs to take into account RWO volumes and quiesced applications (This problem exists in migmigration controller as well, some storage classes allow multiple pods on same node for RWO volumes)
- [ ] Convert ROX volumes to RWO on destination then revert to ROX to perform copy and maintain access mode
- [ ] Storage class conversion + access mode compatibility/validation between clusters on a per-volume basis
- [ ] Ensure PVCs are bound on destination prior to starting rsync copy
- [ ] SSH key needs to be stored in a secret
- [ ] Be more resilient to existing certs+ssh keys on source+destination clusters (PATCH existing secrets on every migration run)
- [ ] Find relevant resources that need to be compared and patched at reconciliation time (https://github.com/konveyor/mig-controller/pull/711/files#r513851410)
 
Nice to haves for v.1.4.0:

- [ ] Rework reconciliation loop to be idempotent
- [ ] Investigate helpful logs from stunnel/rsyncd pods and bubble up to migmigration controller upon error
- [ ] Unit tests for all functions used by controller
- [ ] TLS v1.2 vs v1.3?
